package latihan;

import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lndra
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teksubah = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cekbold = new javax.swing.JCheckBox();
        cekitalic = new javax.swing.JCheckBox();
        cekbesar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teksubah.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        teksubah.setText("Teks Ini Nanti Akan diubah");

        jLabel2.setText("Ubah huruf:");

        cekbold.setText("Bold");
        cekbold.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cekboldStateChanged(evt);
            }
        });

        cekitalic.setText("Italic");
        cekitalic.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cekitalicStateChanged(evt);
            }
        });
        cekitalic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekitalicActionPerformed(evt);
            }
        });

        cekbesar.setText("Perbesar");
        cekbesar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                cekbesarStateChanged(evt);
            }
        });
        cekbesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekbesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teksubah, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cekitalic)
                            .addComponent(cekbold)
                            .addComponent(cekbesar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(teksubah, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cekbold))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cekitalic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cekbesar)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cekitalicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekitalicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cekitalicActionPerformed

    private void cekbesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekbesarActionPerformed
        // TODO add your handling code here:
        Font besar=new Font ("Tahoma", Font.BOLD,30);
       Font biasa=new Font ("Tahoma", Font.PLAIN,24);
        if(cekbesar.isSelected()){
            teksubah.setText(teksubah.getText());
            teksubah.setFont(besar);
        }
        else
        {
            teksubah.setText(teksubah.getText());
            teksubah.setFont(biasa);
        }
    }//GEN-LAST:event_cekbesarActionPerformed

    private void cekboldStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cekboldStateChanged
        // TODO add your handling code here:
       Font tebal=new Font ("Tahoma", Font.BOLD,24);
       Font biasa=new Font ("Tahoma", Font.PLAIN,24);
        if(cekbold.isSelected()){
            teksubah.setText(teksubah.getText());
            teksubah.setFont(tebal);
        }
        else
        {
            teksubah.setText(teksubah.getText());
            teksubah.setFont(biasa);
        }
        
    }//GEN-LAST:event_cekboldStateChanged

    private void cekbesarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cekbesarStateChanged
        // TODO add your handling code here:
        Font tebal=new Font ("Tahoma", Font.BOLD,30);
       Font biasa=new Font ("Tahoma", Font.PLAIN,24);
        if(cekbesar.isSelected()){
            teksubah.setText(teksubah.getText());
            teksubah.setFont(tebal);
        }
        else
        {
            teksubah.setText(teksubah.getText());
            teksubah.setFont(biasa);
        }
    }//GEN-LAST:event_cekbesarStateChanged

    private void cekitalicStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_cekitalicStateChanged
        // TODO add your handling code here:
        Font miring=new Font ("Tahoma", Font.ITALIC,24);
       Font biasa=new Font ("Tahoma", Font.PLAIN,24);
        if(cekitalic.isSelected()){
            teksubah.setText(teksubah.getText());
            teksubah.setFont(miring);
        }
        else
        {
            teksubah.setText(teksubah.getText());
            teksubah.setFont(biasa);
        }
    }//GEN-LAST:event_cekitalicStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cekbesar;
    private javax.swing.JCheckBox cekbold;
    private javax.swing.JCheckBox cekitalic;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel teksubah;
    // End of variables declaration//GEN-END:variables
}
